package com.mycompany.lab_prueba1;

import javax.swing.JOptionPane;

public class PalabraFijoWIN extends javax.swing.JFrame {   
    public static String palabraFija;
    /**
     * Creates new form InicializarPalabrasFijo
     */
    public PalabraFijoWIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palabraFIELD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fijarPalabraBTN = new javax.swing.JButton();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        palabraFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraFIELDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Palabra Fija");

        fijarPalabraBTN.setBackground(new java.awt.Color(51, 51, 255));
        fijarPalabraBTN.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        fijarPalabraBTN.setForeground(new java.awt.Color(255, 255, 255));
        fijarPalabraBTN.setText("Fijar Palabra");
        fijarPalabraBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fijarPalabraBTNActionPerformed(evt);
            }
        });

        volverBTN.setBackground(new java.awt.Color(51, 0, 255));
        volverBTN.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        volverBTN.setForeground(new java.awt.Color(255, 255, 255));
        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palabraFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(volverBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(fijarPalabraBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(palabraFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fijarPalabraBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fijarPalabraBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fijarPalabraBTNActionPerformed
        String  palabra=palabraFIELD.getText();
        palabraFija=palabra;
        JOptionPane.showMessageDialog(null, "Palabra Fijada");
        
        new MainMenuWIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fijarPalabraBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        new MainMenuWIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBTNActionPerformed

    private void palabraFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palabraFIELDActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fijarPalabraBTN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField palabraFIELD;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
